### ISSUE TITLE
[Bug]: Deploy Signed WDAC are not deploying in Windows Server

### ISSUE THREAD

**Issue by dennyamarojr** [HotCakeX/Harden-Windows-Security#117]
### Tools category

WDACConfig Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

Hi @HotCakeX 

I follow your video that shows how to create a code signing certificate for WDAC
https://www.youtube.com/watch?v=vlu1HGuYPeg

But, I had some issues not sure what exactly I'm doing wrong. I Repeat the process 3 times and always end with the following result
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/36896116/805acf7c-4fcd-4237-8aa7-010decf67746)
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/36896116/c99bdd2a-b914-4e6d-a3fa-0a27efb1a7f4)

Maybe I'm creating the certificate with wrong setting? I repeat every step from your video

**Comment by HotCakeX** [comment]
Hi,
In the screenshots I see you first deployed the Default Microsoft policy (unsigned), but then you're using `Deploy-SignedWDACConfig` cmdlet to deploy the same policy in signed mode.

Since i uploaded that video, I made a few changed to improve the WDACConfig module, one of them is not deploying the Signed policy by default on the system. Now you need to use `-Deploy` parameter if you want to deploy it, otherwise it will just create the CIP file. I did it so that if you want to deploy the policy on another computer then you won't have to install the module there.

https://github.com/HotCakeX/Harden-Windows-Security/wiki/Deploy-SignedWDACConfig#signs-and-deploys-a-wdac-policy

**Comment by dennyamarojr** [comment]
Ok, I understand now, I was thinking that was me doing something wrong. And yes I deploy the unsigned one to check something and will try it now. Testing a few thing from the WDAC Module, to implement in my personal computer, your script make things pretty easy ty <3

**Comment by dennyamarojr** [comment]
Maybe you could add some info in the description of the video, just in case someone do the same mistake from missing the -Deploy in the command or just follow the video 😄

**Comment by HotCakeX** [comment]
Glad to know that!
Btw all the documents are up to date in the Wiki/website

I think this scenario is what you're trying to do:
https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-policy-for-Fully-managed-device---Variant-3

Yes ^^ I will soon record and upload new videos. both Windows server insider and WDACConfig module have changed a lot since then!

**Comment by dennyamarojr** [comment]
> I think this scenario is what you're trying to do: https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-policy-for-Fully-managed-device---Variant-3
> 

Yes this is the scenario I'm trying to apply, thanks for the link. Will follow all the steps and make sure I read everything and try not missing any parameter from the module.

**Comment by HotCakeX** [comment]
> > I think this scenario is what you're trying to do: https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-policy-for-Fully-managed-device---Variant-3
> 
> Yes this is the scenario I'm trying to apply, thanks for the link. Will follow all the steps and make sure I read everything and try not missing any parameter from the module.

Let me update it in a sec 🙂

**Comment by dennyamarojr** [comment]
Thank you @HotCakeX I will keep follow the repository and report any issue or provide feedback for improve the modules and scripts.

**Comment by HotCakeX** [comment]
> Thank you @HotCakeX I will keep follow the repository and report any issue or provide feedback for improve the modules and scripts.

Sounds great ^^ Ty!
Just updated all of the documentations, PR: https://github.com/HotCakeX/Harden-Windows-Security/pull/118

If you notice any other discrepancy no matter how small, please open an issue or a pull request so we can fix it!

**Comment by dennyamarojr** [comment]
HI @HotCakeX I test all the settings available and currently I suggest to update the videos from the Wiki as Old and warn the users from missing command in the Wiki. For example the New-WDACConfig parameter make from the audit events, in the video from youtube it shows an old command and persons could get some issues and since I was checking the Wiki I could find the right command and create the WDAC successfully.

**Comment by HotCakeX** [comment]
@dennyamarojr Yes, I'm gonna upload at least 6 new videos and unlist the old ones on YouTube, will add the links to the videos in each wiki page too. Should be done by tomorrow

**Comment by HotCakeX** [comment]
Hi @dennyamarojr 

I've release a new version of WDACConfig module, version 0.2.3: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/WDACConfigv0.2.3

Also uploaded the videos, unlisted the old ones from YouTube, updated the guides etc. This is the PR for the changes: https://github.com/HotCakeX/Harden-Windows-Security/pull/119

Thanks again, I'm marking this issue as completed 😇

<br>

<a href="https://youtu.be/RSYJ64BlS9Y?si=t6TlcYzsMwteG1M9"><img src="https://raw.githubusercontent.com/HotCakeX/.github/main/Pictures/PNG%20and%20JPG/YouTube%20Video%20Thumbnails/With%20YouTube%20play%20button/How%20to%20Create%20and%20Deploy%20a%20Signed%20WDAC%20Policy.png"></a>

<br>

<a href="https://youtu.be/KD0zUb2GCyk?si=_g09D0yF5lTN1NLO"><img src="https://raw.githubusercontent.com/HotCakeX/.github/main/Pictures/PNG%20and%20JPG/YouTube%20Video%20Thumbnails/With%20YouTube%20play%20button/WDAC%20policy%20for%20Fully%20Managed%20device%20-%20Variant%201.png"></a>
<br>

<br>

<a href="https://youtu.be/QpJt255pHDE?si=eLSRkAQXrkHK8SSh"><img src="https://raw.githubusercontent.com/HotCakeX/.github/main/Pictures/PNG%20and%20JPG/YouTube%20Video%20Thumbnails/With%20YouTube%20play%20button/WDAC%20for%20Fully%20Managed%20Devices%20(2nd%20variant).png"></a>

<br>

<a href="https://youtu.be/41_5ntFYghM?si=2PcCXI7gis6UAJh7"><img src="https://raw.githubusercontent.com/HotCakeX/.github/main/Pictures/PNG%20and%20JPG/YouTube%20Video%20Thumbnails/With%20YouTube%20play%20button/WDAC%20policy%20for%20Fully%20managed%20device%20Variant%203.png"></a>

<br>

<a href="https://youtu.be/AgqhcPV9aPY?si=l_2QPbEAKKVhb9z6"><img src="https://raw.githubusercontent.com/HotCakeX/.github/main/Pictures/PNG%20and%20JPG/YouTube%20Video%20Thumbnails/With%20YouTube%20play%20button/WDAC%20policy%20for%20Fully%20managed%20device%20Variant%204.png"></a>

<br>

<a href="https://youtu.be/RgVf4p9ct90?si=mGdVCnqVlUN_FBWR"><img src="https://raw.githubusercontent.com/HotCakeX/.github/main/Pictures/PNG%20and%20JPG/YouTube%20Video%20Thumbnails/With%20YouTube%20play%20button/WDAC%20policy%20for%20Lightly%20managed%20device.png"></a>

<br>

**Comment by starchturrets** [comment]
Ooh, these new videos look nice. Might just use your powershell module on my own personal device, manual management is pretty annoying.

**Comment by HotCakeX** [comment]
@starchturrets 
Thank you!
