### ISSUE TITLE
[Bug]: Confirm-SystemCompliance error

### ISSUE THREAD

**Issue by Ainatar** [HotCakeX/Harden-Windows-Security#127]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

Hello!

I dont know since when this is happening, but when i try to run the command 'Confirm-SystemCompliance' it fails with this error:

`Confirm-SystemCompliance: The 'Get-SmbServerConfiguration' command was found in the module 'SmbShare', but the module could not be loaded. For more information, run 'Import-Module SmbShare'.`

If i try running the 'Import-Module SmbShare' command it also fails with the next error:

`Import-LocalizedData: Cannot find the PowerShell data file 'SmbLocalization.psd1' in directory
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\SmbShare\es-ES', or in any parent culture directories.`

Any ideas? Thanks in advance.

**Comment by HotCakeX** [comment]
Hi,
What happens when you run this in PowerShell as administrator? 

```powershell
Get-SmbServerConfiguration
```

**Comment by Ainatar** [comment]
> Hi, What happens when you run this in PowerShell as administrator?
> 
> ```powershell
> Get-SmbServerConfiguration
> ```

It displays a lot of info about the config, i can paste it if you need it.

**Comment by HotCakeX** [comment]
This looks like a bug with Windows PowerShell
https://forums.powershell.org/t/smbshare-module-has-no-default-localisation-data-file/5465
https://stackoverflow.com/questions/76200280/smbshare-the-module-could-not-be-loaded

I can reproduce it too with es-ES language pack installed and set as Windows language. I will try to implement a workaround in the module and release an update
Thanks for reporting it!

**Comment by HotCakeX** [comment]
Please use any of the module's cmdlets again to auto update it, the issue is fixed
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.1.6.1
