### ISSUE TITLE
[Bug]: After running the script in full, windows defender shows "You don't have the proper permission to view the page" in the exclusions page

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/Harden-Windows-Security#151]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

I ran the script in full recently. While working on a development task, the Attack surface reduction rule blocked me from running pip.exe in my virtual environment. I went into Windows Defender exclusions page to add an exclusion but it shows the following to me.
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/16762897/0a36aa71-832c-4b74-be27-42eec404163d)

After researching the issue a little, I also found that it wont let me view the Controlled Folder Access exclusion page as well, showing me the same message as above.

Running `Get-MpPreference` on elevated powershell shows `N/A: Administrators are not allowed to view exclusions` for a lot of entries for some reason. I have attached the entire `Get-MpPerference` output as a text file for your reference.

The only setting I changed after running the script was to reenable the Performance mode on Dev Drive using `Set-MpPreference -PerformanceModeStatus Enabled`. Reversing this didn't change anything.

How can I fix this issue on my machine?
[mp_perference.txt](https://github.com/HotCakeX/Harden-Windows-Security/files/13266548/mp_perference.txt)

**Comment by HotCakeX** [comment]
Hi,
This is a new policy added in Microsoft Security Baselines that hides the exclusions list from the local admin. I will create a new policy and add it to the optional overrides today


<img width="1280" alt="image" src="https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/0855d15c-4330-4dcc-b6de-506186793253">

**Comment by HotCakeX** [comment]
By the way your exclusion list is not gone, they are just hidden. After that policy is set to not configured they will be visible again.

**Comment by agpt8** [comment]
Ahh yes! Changing it to Not Configured fixed the issue! Thank you!
And yes, I see the preconfigured apps in the Allow list as well!

**Comment by HotCakeX** [comment]
You're welcome and sorry for releasing the 23H2 update without adding that to the overrides

**Comment by agpt8** [comment]
No issues! Thank you for helping resolve this issue so quickly! 😃

**Comment by HotCakeX** [comment]
Hi, the issue is now fixed, thanks for reporting it, please run the script or module again and use the optional overrides in the Microsoft Security Baselines category.

Release notes: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.2.3
