### ISSUE TITLE
[Bug]: Running the script clears out all the entries in Controlled Folder Access Allow list

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/Harden-Windows-Security#152]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

I ran the script recently and I noticed that the Controlled Folder Access Exclusion list had been cleared. There were some 15 exclusions prior to running this script and all of them were gone. This was confirmed when I checked the output of `Confirm-SystemCompliance`. The count said 15 and the apps were listed before I ran the script.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/16762897/9c382037-aac2-41bd-bb9b-7b0300c95986)

Also, when I try to view the Allow list in the app, I get the following message:

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/16762897/8b40f7e5-a6ac-4f79-b90a-e2f32599bb71)

This is related to #151 

Is clearing the Allow list by design or a bug? Is it possible to preserve this list somehow when the script is run again?

**Comment by HotCakeX** [comment]
The same policy I mentioned here will restore them: https://github.com/HotCakeX/Harden-Windows-Security/issues/151#issuecomment-1794826641

Adding it to the optional overrides 🙂

**Comment by HotCakeX** [comment]
Hi, the issue is now fixed, thanks for reporting it, please run the script or module again and use the optional overrides in the Microsoft Security Baselines category.

Release notes: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.2.3
