### ISSUE TITLE
[Bug]: Broken link in Rationale.md

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/Harden-Windows-Security#166]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

There is a broken link under the section [Which device to use](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-which-device-to-use-) in Rationale.md. Specifically the [!Important] call out, at the very end, the link on "Read More". The Moot inc page says 404 Not Found.

PS: I know its a very tiny bug but couldn't help myself :P

**Comment by HotCakeX** [comment]
Nice catch, thank you, it's fixed 🙂
https://github.com/HotCakeX/Harden-Windows-Security/pull/168
