### ISSUE TITLE
I can't remove this [Bug]: 

### ISSUE THREAD

**Issue by TheG3Project** [HotCakeX/Harden-Windows-Security#169]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

I am trying to remove this and I cant

**Comment by HotCakeX** [comment]
To [remove](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Harden%E2%80%90Windows%E2%80%90Security%E2%80%90Module#remove-the-hardening-measures-described-in-the-readme) the hardening measures:

```powershell
Unprotect-WindowsSecurity
```

To remove the harden Windows security module:

```powershell
Uninstall-Module -Name 'Harden-Windows-Security-Module' -Force -AllVersions
```
