### ISSUE TITLE
[Bug]: Some Windows Defender options not working on Windows 11 VM

### ISSUE THREAD

**Issue by MineRock** [HotCakeX/Harden-Windows-Security#216]
### Tools category

Harden Windows Security Script

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [x] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

I am using VMWare Workstation Pro 17, running a clean installed Windows 11 VM (TPM enabled, Secure Boot on, allocated 8GB RAM and 4 cores, running on the latest PowerShell 7) and while applying the Windows Defender hardening measures, the following MpPreferences fail to apply:
OobeEnableRtpAndSigUpdate, IntelTDTEnabled, PerformanceModeStatus, EnableConvertWarnToBlock, BruteForceProtectionAggressiveness, BruteForceProtectionConfiguredState, BruteForceProtectionMaxBlockTime, RemoteEncryptionProtectionAggressiveness, RemoteEncryptionProtectionConfiguredState, RemoteEncryptionProtectionMaxBlockTime

These options are not listed when I run Get-MpPreferences either. I did not face any issue running these on my laptop running Windows 11. What could be the problem here?

**Comment by HotCakeX** [comment]
Hi,
You need to make sure first you're using the latest Windows 11 build, then restart your computer after update once or twice, then they will become available.

I've seen that behavior many times myself, it's alright just restarting twice after fully updating the system makes them available to you. Those are relatively new features that don't exist in the OS ISO file by default and only come after installing the latest updates. The restarts activate them.

**Comment by HotCakeX** [comment]
@MineRock Hello, I just released an update for the Harden Windows Security module and script that detects the available parameters of the Microsoft Defender and if any of them is unavailable, displays a message about restarting the system to make them available, so there will no longer be an error for it.

https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.4.1
