### ISSUE TITLE
[Bug]: The mootinc link in Rationale.md seems to be unreachable

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/Harden-Windows-Security#223]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

The mooinc link can be found under the "Which device to Use?" section in Rationale.md file. In the Important callout, at the very last of the paragraph says "Read More". This read more is pointed to a mootinc site which seems to be unreachable!

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/16762897/2a1876b7-43c0-4754-ad86-afefa932074a)

**Comment by HotCakeX** [comment]
Thank you very much, fixed it!
https://github.com/HotCakeX/Harden-Windows-Security/commit/c3a2a60926f7013439e07204cda4d9d86354a5e6
