### ISSUE TITLE
[Suggestion]:  Extend Confirm-Systemcompliance to parameter categories to check only defined categories 

### ISSUE THREAD

**Issue by kamellemann** [HotCakeX/Harden-Windows-Security#233]
### Are you sure the Security measure is not already implemented?

- [X] Yes, I have checked and the Security measure I'm suggesting to be implemented is not duplicate. 🫡

### Please explain your new Security measure suggestion

[Suggestion]:  Extend Confirm-Systemcompliance to parameter categories to check only defined categories.
As we can define categories in Protect-WindowsSecurity would be great to check compliance only for categories defined for protection.

**Comment by HotCakeX** [comment]
This sounds good, will do that :)

**Comment by kamellemann** [comment]
Great to hear :-) Thanks & enjoy your weekend!

**Comment by HotCakeX** [comment]
Ty, you as well :3

**Comment by HotCakeX** [comment]
Hi, just implemented the feature you requested ^^
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.3.9

**Comment by kamellemann** [comment]
Great, thanks for your great support and work
