### ISSUE TITLE
[Bug]: Edge GPO

### ISSUE THREAD

**Issue by reuvygroovy** [HotCakeX/Harden-Windows-Security#236]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

In the registry resources you search for this key:
"Registry Keys",Edge,HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\Recommended,BlockThirdPartyCookies,Block 3rd party cookies,DWORD,1,https://learn.microsoft.com/en-us/deployedge/configure-edge-with-mdm

The path is incorrect, but should rather be without the word Reccomended: https://admx.help/?Category=EdgeChromium&Policy=Microsoft.Policies.Edge::BlockThirdPartyCookies

**Comment by HotCakeX** [comment]
It is correct.

This is the actual source, not that website
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#blockthirdpartycookies

<br>

<img width="992" alt="image" src="https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/ffc5cfea-4300-40b4-970c-cb726385ade8">

<br>

<br>

<img width="926" alt="image" src="https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/8216d474-ffb9-414b-84e0-f9c9c083da2d">

**Comment by reuvygroovy** [comment]
From the admx files there are two entries

 <policy class="Both" displayName="$(string.BlockThirdPartyCookies)" explainText="$(string.BlockThirdPartyCookies_Explain)" key="Software\Policies\Microsoft\Edge" name="BlockThirdPartyCookies" presentation="$(presentation.BlockThirdPartyCookies)" valueName="BlockThirdPartyCookies">
      <parentCategory ref="microsoft_edge"/>
      <supportedOn ref="SUPPORTED_WIN7_V77"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>
    <policy class="Both" displayName="$(string.BlockThirdPartyCookies)" explainText="$(string.BlockThirdPartyCookies_Explain)" key="Software\Policies\Microsoft\Edge\Recommended" name="BlockThirdPartyCookies_recommended" presentation="$(presentation.BlockThirdPartyCookies)" valueName="BlockThirdPartyCookies">
      <parentCategory ref="microsoft_edge_recommended"/>
      <supportedOn ref="SUPPORTED_WIN7_V77"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>

And two places in the GPO where they can be defined
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/1325158/eca9abef-4edd-4ca5-83f4-420b3fc3f3c1)


We force this setting (using the 1st option), and not reccomended which can be overridden by the  user.

**Comment by reuvygroovy** [comment]
<policy class="Both" displayName="$(string.BlockThirdPartyCookies)" explainText="$(string.BlockThirdPartyCookies_Explain)" key="Software\Policies\Microsoft\Edge" name="BlockThirdPartyCookies" presentation="$(presentation.BlockThirdPartyCookies)" valueName="BlockThirdPartyCookies">
      <parentCategory ref="microsoft_edge"/>
      <supportedOn ref="SUPPORTED_WIN7_V77"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>
    <policy class="Both" displayName="$(string.BlockThirdPartyCookies)" explainText="$(string.BlockThirdPartyCookies_Explain)" key="Software\Policies\Microsoft\Edge\Recommended" name="BlockThirdPartyCookies_recommended" presentation="$(presentation.BlockThirdPartyCookies)" valueName="BlockThirdPartyCookies">
      <parentCategory ref="microsoft_edge_recommended"/>
      <supportedOn ref="SUPPORTED_WIN7_V77"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>

**Comment by reuvygroovy** [comment]
``<policy class="Both" displayName="$(string.BlockThirdPartyCookies)" explainText="$(string.BlockThirdPartyCookies_Explain)" key="Software\Policies\Microsoft\Edge" name="BlockThirdPartyCookies" presentation="$(presentation.BlockThirdPartyCookies)" valueName="BlockThirdPartyCookies">
      <parentCategory ref="microsoft_edge"/>
      <supportedOn ref="SUPPORTED_WIN7_V77"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>
    <policy class="Both" displayName="$(string.BlockThirdPartyCookies)" explainText="$(string.BlockThirdPartyCookies_Explain)" key="Software\Policies\Microsoft\Edge\Recommended" name="BlockThirdPartyCookies_recommended" presentation="$(presentation.BlockThirdPartyCookies)" valueName="BlockThirdPartyCookies">
      <parentCategory ref="microsoft_edge_recommended"/>
      <supportedOn ref="SUPPORTED_WIN7_V77"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>

**Comment by reuvygroovy** [comment]
I can't paste the XML from the admx so here is a screenshot which shows both:
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/1325158/d78b285d-c838-4d02-8ad0-25b08ae77c6d)

**Comment by HotCakeX** [comment]
@reuvygroovy I know. You can see that in the readme that I set it as recommendatory policy because setting it to blocked for all users can break websites that rely on 3rd party cookies.
