### ISSUE TITLE
[Suggestion]: explain Microsoft Surface security more precisely

### ISSUE THREAD

**Issue by oppressor1761** [HotCakeX/Harden-Windows-Security#253]
### Are you sure the Security measure is not already implemented?

- [X] Yes, I have checked and the Security measure I'm suggesting to be implemented is not duplicate. 🫡

### Please explain your new Security measure suggestion

Microsoft Surface for consumers is not secured-core.
Microsoft Surface with Intel does not have Pluton.

**Comment by HotCakeX** [comment]
Hi,
Are you referring to this page and you want me to add the info to it?
https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-which-device-to-use-

**Comment by HotCakeX** [comment]
@oppressor1761 Having the Pluton security chip is not a requirement for Secured-Core certification. Pluton is great to have but Secured-Core PC specifications don't require it.

All of the business edition Surface devices are Secured-Core, they can have Intel, AMD or ARM CPUs.

Non-business surface devices are also very secure, they just don't have one item from the Secure-Core specifications, which is System Guard Secure Launch.

Please have a look at [this article](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Device-Guard-and-Virtualization-Based-Security-in-Windows#device-protection-in-windows-security-gives-you-one-of-these-4-hardware-scores) for Secure-Core specification details.

I've [updated](https://github.com/HotCakeX/Harden-Windows-Security/commit/e39445a6d638db483cd9565f9915e962f6b8eb23) the [Rationale article](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md) based on this issue.
