### ISSUE TITLE
Features to be added to the project

### ISSUE THREAD

**Issue by dennyamarojr** [HotCakeX/Harden-Windows-Security#26]
Hi @HotCakeX ,

Opening a features to be add to the project, so we can know what we should implement to the project and redirect new users if the suggest implementation is already in the project

To be implemented: 

- [x] Add more detail to New-ConfigWDAC and add more scenarios
⛔ Add base templates, so users could have a pre-made template to deploy.
⛔  Create a script to download and install Microsoft Edge templates (Group Policy templates, since the project implement Microsoft recommendations, new devices don't have the admx for Edge Chromium)

Suggestions:

⛔  Add hardening browsers based on CIS benchmarks and adjust to the recommendations to assist the users, by allow stuff like sign to the browser and use share button.
⛔  Implement a pre-made whitelist for Controlled folder access for powershell.exe, cmd.exe, powershell_ise.exe, CiTool.exe and etc.. since if Controlled folder access is enabled, Microsoft Defender will block any changes from this processes.
- [x] Add recommendations for Microsoft Office too, since Microsoft Security Baselines has an guideline for it.

Any updates should be added to this issue, so we can track any future changes to the project and redirect the users to the correct page if is already implemented in the project.

**Comment by dennyamarojr** [comment]
Fork the project and added Office 365 apps for Enterprise Security Baseline
Created a pull request: https://github.com/HotCakeX/Harden-Windows-Security/pull/27

**Comment by HotCakeX** [comment]
Thanks for that, I've been working on updated and completely restructured version of the WDAC module and just got done with it with all wiki posts updated to reflect the changes. Added 2 new functionalities to it as well.

https://www.powershellgallery.com/packages/WDACConfig/

https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig

I'll work on your suggestions next :)

**Comment by dennyamarojr** [comment]
I have been seen you work today and all the WDAC Config is a lot of informations and another thing that could help is Manual Sign to the WDAC template (maybe?) due some enterprise want do manual automation of the template. And also I added a Office security baseline not sure if you check it out @HotCakeX 

But the project is getting a lot of positives ways, so the user will have the freedom to decide the scenarios and which configuration, congrats for the work @HotCakeX

**Comment by dennyamarojr** [comment]
And also feel free to change the info I post here, this should be a good issue to users track updates and help you manage the project too :) @HotCakeX

**Comment by HotCakeX** [comment]
Thank you,

I've reviewed the Edge security baselines and they are suitable for enterprises and businesses, not individuals. Also a lot of those group policies need the presence of a domain controller or AAD. That's why I decided to use registry methods.

<br>

The script and hardening methods used in it set a higher security bar than CIS benchmarks.

>Add base templates, so users could have a pre-made template to deploy.

All of the policies are created on the fly by the module, If I added my own templates then users would need to verify it and spend a lot of time. I take myself out of the equation and only use what Microsoft and Windows use.

>Implement a pre-made whitelist for Controlled folder access for powershell.exe, cmd.exe, powershell_ise.exe, CiTool.exe and etc.. since if Controlled folder access is enabled, Microsoft Defender will block any changes from this processes.

I'm not sure about this one, It can have adverse effects on security of the device. Yes, Controlled Folder Access might block them but for good reasons. Those processes can be used maliciously to harm users data that is protected by CFA. The better alternative is to copy the files you need to work with from the folders protected by CFA to another folder not protected by it, or allow those programs on a case by case basis.

For example, my OneDrive files are very important to me and Controlled Folder Access protects the entire cloud drive while synced on my computer. Instead of adding PowerShell etc. to have access to those folders, I can just copy the file I need and put it somewhere else.

I integrated the Microsoft 365 apps security baseline to the script and testing and checking it, I'll update the script soon and the readme file.

**Comment by dennyamarojr** [comment]
Hi @HotCakeX I see all the updates and also the changes in the repo, good job!
You can also check the boxes when you make the changes, so we can focus on new features to the project 😄

**Comment by dennyamarojr** [comment]
**Updated Changelog 04/09/2023**

Since the following features require additional configurations and has a better way to be implemented, @HotCakeX implemented better explanation and videos to show how you can configure each WDAC rule in different scenarios. Here's a list of the features that will not be implemented as suggested early

Features that will not be implemented: 
⛔  Add base templates, so users could have a pre-made template to deploy. (Since microsoft already provide a pre-made templates, these templates is already enough to users use as a start point).
⛔  Create a script to download and install Microsoft Edge templates (Group Policy templates, since the project implement Microsoft recommendations, new devices don't have the admx for Edge Chromium) - (Like @HotCakeX says "I've reviewed the Edge security baselines and they are suitable for enterprises and businesses, not individuals. Also a lot of those group policies need the presence of a domain controller or AAD. That's why I decided to use registry methods." ) 
⛔  Add hardening browsers based on CIS benchmarks and adjust to the recommendations to assist the users, by allow stuff like sign to the browser and use share button. (The project already offer a better security implementations, so there is no neeed to implement the hardening CIS Benchmarks, additional you could use the system services list provided by CIS Benchmarks as a guideline to hardening the System services of your OS.)
⛔  Implement a pre-made whitelist for Controlled folder access for powershell.exe, cmd.exe, powershell_ise.exe, CiTool.exe and etc.. since if Controlled folder access is enabled, Microsoft Defender will block any changes from this processes. (Different scenarios and a lot of possibilities to not be the desired configuration for the environment, the best way is the users to whitelist the processes that could be executed in the system).

**Comment by HotCakeX** [comment]
Thank you, I've been busy with the WDACConfig module, [added APNGs for each feature.](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig), continuing to expand it with more features.

Those 2 videos I added don't target any specific scenario though, they just show how signed and unsigned application control configurations work in general, using WDACConfig module 😊

I will add text-based wiki posts and probably more videos for other targeted scenarios.

**Comment by dennyamarojr** [comment]
Hi @HotCakeX  I just thinking in something that maybe you already show in the updated videos in WDAC config, that is whitelist the programs,games. But I see that during the whitelist the installation is required (not sure) and if the user already has the program, game installed I don't any question to the user, what did you think @HotCakeX  ?

**Comment by HotCakeX** [comment]
> Hi @HotCakeX I just thinking in something that maybe you already show in the updated videos in WDAC config, that is whitelist the programs,games. But I see that during the whitelist the installation is required (not sure) and if the user already has the program, game installed I don't any question to the user, what did you think @HotCakeX ?

No problem, you can use the same feature to allow an already installed program, installation is not required but browsing for a folder is required.

`AllowNewApps` and `AllowNewAppsAuditEvents` parameters can't detect installation. also, If no audit log is found in the event viewer, then they are safely skipped and only the folder where user selected is scanned. I will make it clearer in the wiki page too :)

**Comment by dennyamarojr** [comment]
That's good, thank you for the information. I will work in the wiki for the WDAC Policy Wizard and them share here with you :)

**Comment by HotCakeX** [comment]
Just finished updating the wiki page with new information for today's module update that brings multiple new features and also made it clearer that the parameters you mentioned allow for apps that are already installed on the system. The module is slowly reaching its maturity, I think, and almost handles any WDAC related operation. A huge number of the features aren't available anywhere else.

https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig

> 0.0.8 New features: Added the last base policy type, DefaultWindows, to the available base policy options to be used for the cmdlets of this module.
> New features: Added -UpdateBasePolicy parameter for the Edit-SignedWDACConfig cmdlet, so you can seamlessly change the base policy type or update block rules in it without changing or redeploying supplemental policies.
> All cmdlets and parameters that create a supplemental policy by scanning now allow optional granular controls over levels and fallback levels, giving user full control over that process.
> Removed underscore (_) from parameter names and now using camel case for all of them.
> Changed parameter set names from generic Set1,Set2 etc. to proper names that can easily identify which parameter they belong to.
> Added [-OnlyBasePolicies] and [-OnlySupplementalPolicies] switches to "Confirm-WDACConfig [-ListActivePolicies]".
> The module now has a total of 23 distinct parameters/features to help easily manage advanced WDAC and Application Whitelisting tasks.

open to more suggestions for new features :)

**Comment by dennyamarojr** [comment]
Hi @HotCakeX I was thinking what about make a question to encrypt the drives available in the system?

For example, Drive C, D, E, F

1 - Do you want encrypt drive C? [Y/N]
1 - Do you want encrypt drive D? [Y/N]
1 - Do you want encrypt drive E? [Y/N]
1 - Do you want encrypt drive F? [Y/N]

**Comment by HotCakeX** [comment]
> Hi @HotCakeX I was thinking what about make a question to encrypt the drives available in the system?
> 
> For example, Drive C, D, E, F
> 
> 1 - Do you want encrypt drive C? [Y/N] 2 - Do you want encrypt drive D? [Y/N] 3 - Do you want encrypt drive E? [Y/N] 4 - Do you want encrypt drive F? [Y/N]


Done 🙂

https://github.com/HotCakeX/Harden-Windows-Security/commit/ebcf32e1bfae6609629618a72dca758b4aed7ba9

**Comment by HotCakeX** [comment]
Hi @dennyamarojr 

I've created 3 new scenarios, completely rewrote everything, fixed all the links etc:

* [WDAC for Lightly managed device](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-for-Lightly-Managed-Devices)
* [WDAC for Fully managed device - Variant 1](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-for-Fully-Managed-Devices)
* [WDAC for Fully managed device - Variant 2](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-for-Fully-Managed-Devices-(2nd-variant))
* [WDAC for Fully managed device - Variant 3](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-policy-for-Fully-managed-device---Variant-3)
* [WDAC for Fully managed device - Variant 4](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-policy-for-Fully-managed-device---Variant-4)

With that, I'm going to close this issue as fixed. Please open a separate new issue whenever there is a new request and/or feedback, Thank you, have a good one! ^^
