### ISSUE TITLE
[Bug]: Default PowerShell Fails

### ISSUE THREAD

**Issue by qf0** [HotCakeX/Harden-Windows-Security#277]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

The installation steps don't work with the default version of PowerShell on the latest Win11 OS. However, Installing PowerShell 7.x worked, so adding that to the instructions would be helpful.

**Comment by agpt8** [comment]
Its already there. That is the first requirement under the requirement section in the [readme](https://github.com/HotCakeX/Harden-Windows-Security#requirements-)

**Comment by HotCakeX** [comment]
Hi, 
As @agpt8 mentioned, the readme has the necessary info.

I made it automated if you try to use it as a script directly from GitHub, but if you decide to install it as a module you have to take care of the PowerShell installation manually which is done from the Microsoft Store.

In the future, I can offer a script to do the installation automatically too and maybe add a desktop icon for the Harden Windows Security module after installation to offer an easy way to start it.

So i'm gonna close this and let you know when more automation is in place. Will make a roadmap soon to track it.
