### ISSUE TITLE
[Bug]: Confirm-SystemCompliance working directory issue

### ISSUE THREAD

**Issue by brutsers** [HotCakeX/Harden-Windows-Security#298]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

![Screenshot 2024-07-11 223933](https://github.com/user-attachments/assets/cf28e945-5fa4-4cf7-b249-ca92d177dfd6)

In the elevated Powershell window on a freshly installed and updated Windows 11 23h2 you can see the exception error when running the Confirm-SystemCompliance script.

The root cause of this problem is the default working directory for .NET when running these elevated commands.
`PS C:\Users\VMUSER> [System.IO.Directory]::GetCurrentDirectory()`
`C:\Windows\system32`

**IniFileConverter.cs** shows where it will go wrong:
`string[] lines = File.ReadAllLines(iniFilePath);`

In this case [System.IO.File]::ReadAllLines('.\security_policy.inf') will look for the file in c:\Windows\system32.

> Suggested solution:

`# Use the always writable and accessible temp directory to export the security_policy.inf`
`$exportFile = Join-Path -Path $env:TEMP -ChildPath "security_policy.inf"`

`# Get the security group policies`
`$null = &"$env:SystemDrive\Windows\System32\Secedit.exe" /export /cfg "$exportFile"`

`# Storing the output of the ini file parsing function`
`$SyncHash['SecurityPoliciesIni'] = [HardeningModule.IniFileConverter]::ConvertFromIniFile($exportFile)`

> Optional:

- You can test the exitcode $null to be sure secedit was not having any problems
- You can verify the $exportFile path and see if it was created successfully

**Comment by HotCakeX** [comment]
Hi,
I'm going to fix this in the next update, in the meantime you can simply use the module without doing any `cd` first, there won't be any errors.

The root cause of this problem is that you change the working directory at some point after loading the module or stopping it during its operation and then run it again, which is still a bug that needs to be fixed but you can avoid doing that for now until next update.

Thanks
