### ISSUE TITLE
[BUG?] TLS Security - Break Battle.net Launcher

### ISSUE THREAD

**Issue by Tumeez** [HotCakeX/Harden-Windows-Security#38]
I noticed that TLS Security breaks Battle.net Launcher.

Virtual Machine: VMWare Workstation Pro 17.0.2 // Win 11 Enterprise 22H2 fresh installed, including all updates up-to-date.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/52361553/ebe3dbc3-250c-4dfa-855e-f6c03514b6d9)

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/52361553/07d3dcca-8797-4546-b783-0000851846dc)

After I apply TLS Security part, the machine can't connect to Battle.net anymore. I test every combination, other parts are okay with Battle.net.

**Comment by HotCakeX** [comment]
Hi,
Please take a look at this thread:
https://github.com/HotCakeX/Harden-Windows-Security/discussions/28

Another user had the same problem. Battle.net requires an old cipher suite which is not very secure and the TLS category disables it, but nevertheless, you can enable it again by running this in an elevated PowerShell:

```powershell
Enable-TlsCipherSuite -Name "TLS_RSA_WITH_AES_256_CBC_SHA"
```

**Comment by Tumeez** [comment]
> Hi, Please take a look at this thread: #28
> 
> Another user had the same problem. Battle.net requires an old cipher suite which is not very secure and the TLS category disables it, but nevertheless, you can enable it again by running this in an elevated PowerShell:
> 
> ```powershell
> Enable-TlsCipherSuite -Name "TLS_RSA_WITH_AES_256_CBC_SHA"
> ```
> 
> Please let me know if that fixes your problem. If it does, I will temporarily move it from TLS category to TopSecurity category since it's causing inconvenience for users, when Battle.net stops using that cipher suite, then I'll return it back to the TLS category.

Test it with my virtual machine. Works very well. After that command, Battle.net launcher works like meant.

**Comment by HotCakeX** [comment]
Great thanks, updated the script with the change 🙂

**Comment by HotCakeX** [comment]
Just a heads up, the script is enforcing a tighter TLS security settings after more careful research.

I've added a warning message to be shown before running the TLS category so that users with Battle.net client can see it and skip the category.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/799f99ef-f53c-4ceb-877c-af6b36381fa6)

I've also tweeted at them about this issue: https://twitter.com/SpyNetGirl/status/1659872718806822916
