### ISSUE TITLE
[Bug]: Web PnP download does not get disabled

### ISSUE THREAD

**Issue by 26zl** [HotCakeX/Harden-Windows-Security#416]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

![Skjermbilde 2024-11-25 142908](https://github.com/user-attachments/assets/1f101b7f-1a56-4c0a-a4e0-1f0b1fe11a43)

It does not return any errors, it simply does not get disabled. Even if i try multiple times. 
I tried to do it manually by changing this in gpedit: "Package Point and Print - Approved Servers" and add a "fake" placeholder value(server/local) to fully disabled it. But still gets marked as false in confirm-system-compliance.

Thanks in advance!

**Comment by HotCakeX** [comment]
Hi, thanks for reporting, i'll look into it and let you know ^^

**Comment by HotCakeX** [comment]
Hi, i verified it on my system and a freshly created VM, both having latest version of the OS.

Edition: Windows 11 Pro
Version: 24H2
OS build: 26100.2314

It is correctly disabled every time. This is the exact registry key used during compliance check: https://github.com/HotCakeX/Harden-Windows-Security/blob/76e6ca7e55848b580e59fdf95b38af895127cb39/Harden-Windows-Security%20Module/Main%20files/Resources/Registry%20resources.csv#L101

**Comment by 26zl** [comment]
> Hi, i verified it on my system and a freshly created VM, both having latest version of the OS.
> 
> 
> 
> Edition: Windows 11 Pro
> 
> Version: 24H2
> 
> OS build: 26100.2314
> 
> 
> 
> It is correctly disabled every time. This is the exact registry key used during compliance check: https://github.com/HotCakeX/Harden-Windows-Security/blob/76e6ca7e55848b580e59fdf95b38af895127cb39/Harden-Windows-Security%20Module/Main%20files/Resources/Registry%20resources.csv#L101
> 
> 
> 
> 

Oh okey! Hmm very weird. I would need to do so debugging then why it wont apply on my system. Everything is latest windows version. Thanks for checking it out !

**Comment by HotCakeX** [comment]
Sorry i couldn't be more helpful. Maybe try removing protection and then re-apply them.

**Comment by 26zl** [comment]
> Sorry i couldn't be more helpful. Maybe try removing protection and then re-apply them.

No need to be sorry at all! Ur more than helpful! Thanks for checking at all!👍🏼
