### ISSUE TITLE
[Bug]: Exception calling "Initialize" with "1" argument(s): "Failed to get MpComputerPreference"

### ISSUE THREAD

**Issue by wahitftry** [HotCakeX/Harden-Windows-Security#428]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

I just ran the Harden Windows Security script for the first time with the command (irm 'https://raw.githubusercontent.com/HotCakeX/Harden-Windows-Security/main/Harden-Windows-Security.ps1')+'P'|iex but I got an error that I don't know where it came from.

![image](https://github.com/user-attachments/assets/de793d1f-d688-4840-a687-eb14e63e5ead)

### Error Details

```console
Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Initialize" with "1" argument(s): "Failed to get MpComputerPreference"
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperationException
        InvocationInfo        :
            ScriptLineNumber : 275
            OffsetInLine     : 9
            HistoryId        : 1
            ScriptName       :
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
            Line             : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)

            Statement        : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)
            PositionMessage  : At
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:275
char:9
                               +         [HardenWindowsSecurity.Initializer]::Initialize($VerbosePrefe …
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
            PSCommandPath    :
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Protect-WindowsSecurity<Begin>,
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:
line 275
                                at <ScriptBlock>, <No file>: line 7
    TargetSite     :
        Name          : CheckActionPreference
        DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Initialize" with "1" argument(s): "Failed to get MpComputerPreference"
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type       : System.InvalidOperationException
        TargetSite :
            Name          : GetMpPreference
            DeclaringType : [HardenWindowsSecurity.MpPreferenceHelper]
            MemberType    : Method
            Module        : ca2ooiip.bap.dll
        Message    : Failed to get MpComputerPreference
        Source     : ca2ooiip.bap
        HResult    : -2146233079
        StackTrace :
   at HardenWindowsSecurity.MpPreferenceHelper.GetMpPreference()
   at HardenWindowsSecurity.Initializer.Initialize(String VerbosePreference, Boolean IsConfirmationDuringRunTime)
   at CallSite.Target(Closure, CallSite, Type, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object
inputToProcess)
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
InvocationInfo        :
    ScriptLineNumber : 275
    OffsetInLine     : 9
    HistoryId        : 1
    ScriptName       :
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
    Line             : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)

    Statement        : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)
    PositionMessage  : At
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:275
char:9
                       +         [HardenWindowsSecurity.Initializer]::Initialize($VerbosePrefe …
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
    PSCommandPath    :
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Protect-WindowsSecurity<Begin>,
C:\Users\wahit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:
line 275
                        at <ScriptBlock>, <No file>: line 7
```

**Comment by HotCakeX** [comment]
There must be a problem on your end, this seems unrelated to the module. Your system is unable to handle a simple CIM method call to get the Defender preferences. Could be because you are using a 3rd party antivirus software that modified your system or using modified OS, or maybe you're using Windows Sandbox that doesn't have the necessary APIs.

**Comment by wahitftry** [comment]
I didnt use a modified OS when installing windows. But I did use malwarebytes and last week I removed it using malwarebytes removal tool. that might be the cause. I'll try reinstalling windows then. thank you for your help

**Comment by HotCakeX** [comment]
> I didnt use a modified OS when installing windows. But I did use malwarebytes and last week I removed it using malwarebytes removal tool. that might be the cause. I'll try reinstalling windows then. thank you for your help

No problem, yes that could be it, the removal tool probably didn't undo all the changes the malware bytes installation made.

**Comment by make-agi-quick** [comment]
> (irm 'https://raw.githubusercontent.com/HotCakeX/Harden-Windows-Security/main/Harden-Windows-Security.ps1')+'P'|iex
Protect-WindowsSecurity:
Line |
   7 |          Protect-WindowsSecurity -GUI
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Initialize" with "1" argument(s): "Failed to get MpComputerPreference"

this problem started happening I can guess it happened due to   winmgmt /resetrepository ?

**Comment by make-agi-quick** [comment]
and this started happening and its not in use ?  Install-Module -Name 'Harden-Windows-Security-Module' -Force
WARNING: The version '0.7.4' of module 'Harden-Windows-Security-Module' is currently in use. Retry the operation after closing the applications.

**Comment by HotCakeX** [comment]
> > (irm '[https://raw.githubusercontent.com/HotCakeX/Harden-Windows-Security/main/Harden-Windows-Security.ps1')+'P'|iex](https://raw.githubusercontent.com/HotCakeX/Harden-Windows-Security/main/Harden-Windows-Security.ps1')+'P'%7Ciex)
> > Protect-WindowsSecurity:
> > Line |
> > 7 |          Protect-WindowsSecurity -GUI
> > |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > | Exception calling "Initialize" with "1" argument(s): "Failed to get MpComputerPreference"
> 
> this problem started happening I can guess it happened due to winmgmt /resetrepository ?

I'm not sure what you mean by that?
