### ISSUE TITLE
Upcoming Windows change: MDAV performance mode is bad for your security and needed only in very specific cases (developers)

### ISSUE THREAD

**Issue by rafalfitt** [HotCakeX/Harden-Windows-Security#43]
"The goal of performance mode is to improve functional performance for developers who use Windows 11 devices."

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-antivirus-performance-mode

**Comment by rafalfitt** [comment]
"Performance mode is enabled by default when a new Dev Drive is created."

**Comment by rafalfitt** [comment]
+ 'Performance mode can only run on a “trusted” Dev Drive.'

**Comment by HotCakeX** [comment]
Hi,
It's currently in Windows insider Dev channel builds
https://learn.microsoft.com/en-us/windows/dev-drive/#prerequisites

There isn't a Group Policy in stable builds to control it. The commands to query or assign trust to it also don't work on stable builds when I run them, I use beta build for day to day usage.
https://learn.microsoft.com/en-us/windows/dev-drive/#how-do-i-configure-additional-security-filters-on-dev-drive

So if someone is using insider builds and they use dev drive, they can change the Microsoft Defender's behavior with those commands.

That's my idea, let me know what you think :)

**Comment by rafalfitt** [comment]
"Performance mode is enabled by default when a new Dev Drive is created."
so this Powershell is not needed and can be safely removed.

**Comment by HotCakeX** [comment]
> "Performance mode is enabled by default when a new Dev Drive is created." so this Powershell command is not needed and can be safely removed.

Which PowerShell command?

**Comment by rafalfitt** [comment]
(please ignore my previous comment, my mistake)

**Comment by HotCakeX** [comment]
This was just added to the beta channel
https://blogs.windows.com/windows-insider/2023/08/02/announcing-windows-11-insider-preview-build-22621-2129-and-22631-2129/

I've been testing it, couldn't find a group policy for it yet but we can mark a Dev drive as untrusted and restore its protection using fsutil

```powershell
fsutil devdrv untrust <Drive Letter>
```

**Comment by HotCakeX** [comment]
Added the feature to disable the performance mode in Microsoft Defender for Dev drives

https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/v2023.08.20
