### ISSUE TITLE
[Bug]: (0x800B010A) Error While Installing AppControl Manager

### ISSUE THREAD

**Issue by KEANU2003** [HotCakeX/Harden-Windows-Security#430]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

There is a problem when I try to install the application in any way 
a photo from error:
![20241129_003414](https://github.com/user-attachments/assets/b2b3f704-b3bc-4f8d-9d3b-ff7753b631ce) 

This is the full error text: 
This application package's publisher certificate could not be verified. Contact your system administrator or the application developer to obtain a new application package with verified certificates. The root certificate and all immediate signature certificates in the application package need to be verified (0x800B010A) 

Error code: CERT_E_CHAINING 

Value: 0x800B010A 
Description and possible causes: A certificate chain could not be built to a trusted root certification authority, see [Signing a package](https://learn.microsoft.com/en-us/previous-versions/br230260(v=vs.110)).

**Comment by HotCakeX** [comment]
The installation method is described here:
https://github.com/HotCakeX/Harden-Windows-Security/wiki/AppControl-Manager#how-to-install-or-update-the-app

**Comment by KEANU2003** [comment]
i tried that method, too.
that also does not work for me.

**Comment by HotCakeX** [comment]
@KEANU2003 If the error was about unsupported OS version, i just pushed an update that lets the app be installed on 23H2. please try again and if you see an error let me know: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/AppControlManager.v.1.5.2.0
