### ISSUE TITLE
AppControl Manager needs to be supported on 23H2

### ISSUE THREAD

**Issue by HotCakeX** [HotCakeX/Harden-Windows-Security#435]
Originally discussed here: https://github.com/HotCakeX/Harden-Windows-Security/discussions/434

to make it more available, it should be able to install on 23H2 and features that aren't compatible should be disabled/configured.

**Comment by bladehstream** [comment]
This would be terrific; I know a lot of enterprises have a slow release cycle and some still run with Windows 10. Supporting these environments would be great, and reboots aren't a problem!

**Comment by HotCakeX** [comment]
@bladehstream You can now use it on 23H2: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/AppControlManager.v.1.5.2.0
