### ISSUE TITLE
[Bug]: Small bug in WindowsFeatureChecker.cs

### ISSUE THREAD

**Issue by hardwarebxl** [HotCakeX/Harden-Windows-Security#449]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

InternetPrintingClient = optionalFeatureStates.GetValueOrDefault("Printing-Foundation-Features", "Unknown")

should be:
InternetPrintingClient = optionalFeatureStates.GetValueOrDefault("Printing-Foundation-InternetPrinting-Client", "Unknown")

Because now the Internet Printing check will always see it as Enabled, even when it's not.

**Comment by hardwarebxl** [comment]
You could also fix when a feature is completely removed, you check for Disabled for example with WorkFolders, but if the feature is removed, it should still report True same with other settings you check. Not big deal, but more accurate imo.

**Comment by HotCakeX** [comment]
Hi,
Thank you for creating this issue, I've fixed it here
https://github.com/HotCakeX/Harden-Windows-Security/pull/453/commits/4df5c5e303b9734b4a21717876039510a58a48c2

<br>

This is how it looks like now

![image](https://github.com/user-attachments/assets/90655bdf-4ada-4caf-8db8-a522fcfe81bf)

<br>

If a feature that needs to be removed doesn't exist in a version of Windows, its status is shown as unknown, but it is still marked as compliant.
