### ISSUE TITLE
Increase the firewall log max. size

### ISSUE THREAD

**Issue by Harvester57** [HotCakeX/Harden-Windows-Security#52]
Hi,

Two small improvements regarding the firewall policy:

- Split the log in separate files for each profile (such as publicfw.log, privatefw.log and domainfw.log). This is recommended in the CIS Benchmark policy
- Increase the maximum size of each logs to their upper limit (32MB, so 32767 for the LogFileSize registry keys)

**Comment by HotCakeX** [comment]
Hi,
Thank you for the issue ^^

https://github.com/HotCakeX/Harden-Windows-Security/commit/d8192d6643e14ac193b2b055d2b8214e659d1d2c

**Comment by HotCakeX** [comment]
Old vs new policy

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/de97f3c2-fd32-442b-9692-1dbb6fa2c2ea)

**Comment by Harvester57** [comment]
Very nice, thanks !
