### ISSUE TITLE
Against script injections in PowerShell

### ISSUE THREAD

**Issue by keneos-dev** [HotCakeX/Harden-Windows-Security#59]
Script injections capable of bypassing Windows Defender with all the security and cloud options enabled [are easy to find](https://infosecwriteups.com/evading-detection-with-hoaxshell-obfuscation-a-tool-to-bypass-windows-defender-a6fd56ad27b4). Among [its recommendations](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/security/preventing-script-injection) on the subject, Microsoft recommends [installing and configuring InjectionHunter](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/security/preventing-script-injection?view=powershell-7.3#detecting-vulnerable-code-with-injection-hunter). [Constrained language mode](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/) is [also mentioned](https://learn.microsoft.com/en-us/powershell/scripting/learn/security-features?view=powershell-7.3#constrained-language-mode).

**Comment by HotCakeX** [comment]
Hi,
There is no problem or concern about it. let me explain in details,

In the Medium post he says "On Windows 10 victim, I have all the security options enabled, and it’s fully updated and patched."

But all he shows is this screenshot

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/4c1bef4d-3f5f-4133-8268-75e877e297bd)

But that's not even half of the ***all the security options*** available on Windows 10.

All of those shown in the screenshot, and a lot more, are already enabled by default on the latest Windows 11 update.

He again incorrectly mentions the same thing further down in his post "All the security options are enabled while we still have the shell running on our victim machine, thus indicating that the payload is undetected."

<br>

Another problem with that post. AmsiTrigger_x64.exe is required to exist on the victim's computer. That's not going to happen with this Windows hardening script and all the features it turns on.

This is the SmartScreen message for people trying to download it:

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/5f85e1d4-14c0-43fe-83de-6b4b60259fd5)

Users must intentionally download that tool, and go out of their way to force Edge to download it, which means they do want to be compromised at this point.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/34bccb0b-047b-4624-9e9d-851a02883b93)

Also that tool is **unsigned**, that's another red flag.

<br>

The web page you linked to is correct about PowerShell constrained language mode
https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/

But as it mentions, it should be used with WDAC to be effective, and my repository has a lot of content about it, especially the [WDACConfig module.](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig)

Neither the module nor the script uses any unsafe methods as far as I know. The only time invoke-expression is used is on the GitHub Readme page itself for easier/quicker consumption but there is also option to use PowerShell gallery so it can be completely avoided.

This page is good too, explaining how not to use unsafe stuff, I'll try the Injection Hunter module, Thanks!
https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/security/preventing-script-injection?view=powershell-7.3

<br>

For a good penetration test, I've written the steps that need to be taken, Pen testers and Red teamers can use them for a realistic scenario

https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-for-penetration-testing-and-benchmarking

**Comment by keneos-dev** [comment]
Alright, thank you for this detailed answer! 🙏
