### ISSUE TITLE
Add secure deletion

### ISSUE THREAD

**Issue by keneos-dev** [HotCakeX/Harden-Windows-Security#60]
Why not add [SDelete](https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete) and integrate it [into the context menu](https://www.majorgeeks.com/content/page/how_to_add_secure_delete_to_the_context_menu.html) (and maybe recycle bin management)? Just a suggestion, as secure deletion is part of security. The updated DoD 5220.22-M ECE method requires seven passes, the command to reach this standard is: `sdelete -p 7 -r -s C:\SensitiveData`. I'm not sure about SDelete's compatibility with SSDs though.

**Comment by HotCakeX** [comment]
Thank you for this,
To protect data at rest, the script uses Bitlocker to encrypt both used and free space of OS drive and [optionally] any other drive.
That makes existing and deleted data inaccessible to unauthorized individuals.

However, your suggestion is great and i'd like to implement it in addition to the Bitlocker protection. I do need help with implementing it in the new Windows 11's context menu, it's different than the simple registry key modifications required for the regular context menu, AFAIK new context menu style requires an app to be installed before it can add context menu entries. If it's too much work I guess the old context menu is enough for now.

I'm thinking we can add a new optional step to the Bitlocker category where the script downloads SDelete from Microsoft website, puts it in a location that is inside the PATH env variable for the System and then add it to the context menu for file deletion.

Something else that'd be cool to have is automating the process so when user empties the recycle bin, files will be actually deleted using the highly secure unrecoverable methods.

**Comment by HotCakeX** [comment]
> > I'm not sure about SDelete's compatibility with SSDs though.
> 
> I read conflicting information on the subject, people saying [it's useless](https://superuser.com/a/1597155)/[doesn't work](https://forums.grc.com/threads/sdelete-with-wear-leveling-ssd.549/) on an SSD, and people saying [the opposite](https://superuser.com/a/1597148). If it's useless, maybe it's better to avoid shortening the SSD's lifespan with rewrites.
> 
> > Something else that'd be cool to have is automating the process so when user empties the recycle bin, files will be actually deleted using the highly secure unrecoverable methods.
> 
> Perhaps by [changing the "Empty Recycle Bin" menu entry](https://answers.microsoft.com/en-us/windows/forum/all/change-empty-recycle-bin-icon-and-text-in-context/db1625f0-9a86-41e1-ba85-a7eb4afb6e37) so that it uses SDelete?

Thanks!
Those are good points for sure. Looks like full disk encryption is the best proactive solution. Those rewrites will definitely shorten SSD's lifespan gradually, possibly 7 times quicker than normal deletion operations.

I've never personally sold storage devices before, either destroyed them or kept using them till they stop working and then destroy them.

Maybe we can still provide SDelete optionally for people willing to sacrifice SSD lifespan for greater security/peace of mind/etc.

**Comment by HotCakeX** [comment]
> > Btw I checked out the MS answers post, they are changing the name of the context menu entry, i'd need to be able to change the action assigned to it as well.
> 
> Yes, normally there is an entry for the command in the same registry folder. I was just able to find `HKEY_CLASSES_ROOT\CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\shell\empty\command` which has a DelegateExecute entry with GUID `{48527bb3-e8de-450b-8910-8c4099cb8624}`, so if I understand correctly you'd have to [find and modify the associated shell extension](https://devblogs.microsoft.com/oldnewthing/20100312-01/?p=14623) (`shell32.dll`)? The registry is a real maze and I'm not sure what I'm doing. 😅 There may be a simpler entry somewhere, but I haven't been able to find it.

I'll ask BingChat see if it can assist in this 👀

**Comment by pathei-kosmos** [comment]
Modifying `shell32.dll` seems like a bad idea though. 👀

**Comment by pathei-kosmos** [comment]
I've looked into the matter further, and the usual secure deletion, which [I believe SDelete uses](https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete#how-sdelete-works), is indeed [quite unreliable on SSDs](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9171922). Apparently you'd have to use [ATA Secure Delete](https://csrc.nist.gov/glossary/term/secure_erase_command), which is [rather complicated to set up on Windows](https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/security-group-commands#secure-erase). The other option is to use the SSD management software supplied by the manufacturer. So encryption seems to be the best option [[1]](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9169005) [[2]](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9170106). Bottom line is: nobody really knows [[3]](https://security.stackexchange.com/a/62259) [[4]](https://security.stackexchange.com/a/64480), but the BitLocker encryption that the script already provides should do the trick.

**Comment by HotCakeX** [comment]
> I've looked into the matter further, and the usual secure deletion method, which [I believe SDelete uses](https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete#how-sdelete-works), is indeed [quite unreliable on SSDs](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9171922). Apparently you'd have to use [ATA Secure Delete](https://csrc.nist.gov/glossary/term/secure_erase_command), which is [rather complicated to set up on Windows](https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/security-group-commands#secure-erase). One other option is to use the SSD management software supplied by the manufacturer. So encryption seems to be the best option [[1]](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9169005) [[2]](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9170106) [[3]](https://community.spiceworks.com/topic/2317507-how-to-ata-secure-erase-for-ssd#entry-9274842). Bottom line is: nobody really knows [[4]](https://security.stackexchange.com/a/62259) [[5]](https://security.stackexchange.com/a/64480), but the BitLocker encryption that the script already provides should do the job [[6]](https://security.stackexchange.com/a/255154) [[7]](https://security.stackexchange.com/a/255805)... 🤞

Thank u so much! 🙏

I think that's the best answer, going to close the issue as completed because the solution is already present in the script, and others mentioned in your post such as physical destruction are great for when you're done with the storage device.
