### ISSUE TITLE
Hardening LSASS process

### ISSUE THREAD

**Issue by keneos-dev** [HotCakeX/Harden-Windows-Security#61]
I may have missed it, but I couldn't find any activation of `RunAsPPL` in the registry. This could be [a simple but effective security measure](https://itm4n.github.io/lsass-runasppl/), [endorsed by Microsoft](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn408187(v=ws.11)#on-x86-based-or-x64-based-devices-using-secure-boot-and-uefi-or-not), in addition to the UEFI lock.

**Comment by HotCakeX** [comment]
Hi,
only very few security measures are applied using registry, those that can't be enabled using Group Policy or PowerShell cmdlets.

<br>

This one is enabled using Group policy in the Device Guard category
https://github.com/HotCakeX/Harden-Windows-Security#device-guard

<br>

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/9bc30bff-dc75-42df-b375-88f35bfa1057)

**Comment by keneos-dev** [comment]
Oh, my mistake. Thank you! 🙏

**Comment by keneos-dev** [comment]
Oh, my mistake. Thank you! 🙏

**Comment by HotCakeX** [comment]
> Oh, my mistake. Thank you! 🙏

You're welcome, no worries 🙂
