### ISSUE TITLE
[New Security Measure Suggestion]: 

### ISSUE THREAD

**Issue by IronBamBam1990** [HotCakeX/Harden-Windows-Security#82]
### Are you sure the Security measure is not already implemented?

- [X] Yes, I have checked and the Security measure I'm suggesting to be implemented is not duplicate. 🫡

### Please explain your new Security measure suggestion

Yo i wanna present also Reset solution:

Go to Start (open the Start menu) > Run (open the Run app), and type 'cmd' (without the quotes) and press Enter. [Or open the Start menu and then run the Command Prompt program.]

RD /S /Q "%WinDir%\System32\GroupPolicyUsers"
RD /S /Q "%WinDir%\System32\GroupPolicy"
gpupdate /force /boot

**Comment by HotCakeX** [comment]
Hi,
good suggestion, I can add something like that to the module but it goes beyond group policy since some settings are applied by cmdlets and registry keys.

**Comment by HotCakeX** [comment]
Hi,
I just released an update that added this new functionality to the module
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.0.9
