### ISSUE TITLE
[Bug]: Invoke-WebRequest: 404: Not Found

### ISSUE THREAD

**Issue by Mind777** [HotCakeX/Harden-Windows-Security#83]
### Tools category

WDACConfig Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Please explain the bug

PowerShell 7.3.6
PS C:\Users\*> Install-Module -Name WDACConfig -Force
PS C:\Users\*> New-WDACConfig -SetAutoUpdateDriverBlockRules

TaskPath                                       TaskName                          State
--------                                       --------                          -----
\MSFT Driver Block list update\                MSFT Driver Block list update     Ready
\MSFT Driver Block list update\                MSFT Driver Block list update     Ready

The document containing the drivers block list on GitHub was last updated on 07/13/2023 15:53:45
Invoke-WebRequest: 404: Not Found

**Comment by HotCakeX** [comment]
Hi, thanks for letting me know!
The GitHub links for Microsoft documents were changed that's why it happened, I replaced the old links with the new ones, will release an update later today with a few more improvements!

**Comment by HotCakeX** [comment]
Issue is fixed, thank you

https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/WDACConfigv0.2.1

**Comment by Mind777** [comment]
Thanks!
