### ISSUE TITLE
[Bug]: Error in "Untrusted Fonts" Category on Non-English Systems

### ISSUE THREAD

**Issue by starraiderx** [HotCakeX/Harden-Windows-Security#87]
### Tools category

Harden Windows Security Script

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Description:

On systems not using "English (US)" as the language, blocking untrusted fonts results in an error with the message `Fehler 0x00000057: Falscher Parameter`.

### Steps to Reproduce:

1. On a system with a language other than "English (US)", navigate to the "Block Untrusted Fonts" section.
2. Select the option to block untrusted fonts.
3. Observe the error message: `Fehler 0x00000057: Falscher Parameter`.

### Additional Information:

The error seems related to the `AuditPol` command's parameters or localization.

### Below is the full output:

```
Block Untrusted Fonts ?
1: Yes
2: No
3: Exit
Select an option: 1
Web request status [Web request completed. (Number of bytes processed: 95238)                                        ]
LGPO.exe - Local Group Policy Object Utilitylaneous Configurations section                                           ]
Version 3.0.2004.13001
Copyright (C) 2015-2020 Microsoft Corporation
Security Compliance Toolkit - https://www.microsoft.com/download/details.aspx?id=55319

Web request status [Web request completed. (Number of bytes processed: 95238)                                        ]is
Miscellaneous Configurations [Running Miscellaneous Configurations section                                           ]
Fehler 0x00000057:
Falscher Parameter.

Syntax: Befehl AuditPol [<Unterbefehl><Optionen>]


Befehle (nur ein Befehl pro Ausführung zulässig)
  /?             Hilfe (kontextabhängig)
  /get           Zeigt die aktuelle Überwachungsrichtlinie an.
  /set           Legt die Überwachungsrichtlinie fest.
  /list          Zeigt die auswählbaren Elemente der Richtlinie an.
  /backup        Speichert Überwachungsrichtlinien in einer Datei.
  /restore       Stellt eine Überwachungsrichtlinie aus einer Datei wieder her.
  /clear         Löscht die Überwachungsrichtlinie.
  /remove        Entfernt die Einzelbenutzer-Überwachungsrichtlinie für
                 einen angegebenen Benutzer.
  /resourceSACL  Konfiguriert SACLs für globale Ressourcen
```

**Comment by HotCakeX** [comment]
Thank you for reporting it! I'm going to fix it right away!

**Comment by HotCakeX** [comment]
Added the fix to the update, please confirm it's fixed for you too
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/v2023.08.20
