### ISSUE TITLE
Idk what it does 💀

### ISSUE THREAD

**Issue by stunlocked1** [HotCakeX/Harden-Windows-Security#88]
### Tools category

Harden Windows Security Script

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Please explain the bug

But i said 1 to all of the Things 👍

i think it installed Cheats on my pc how do i use them tho? i red the hole Page for this and couldnt find it. Theres Nothing On my desk top

**Comment by HotCakeX** [comment]
Everything is explained in the Readme with official references, you can click on each hyperlinked text and open the relevant page. Closing this.

**Comment by stunlocked1** [comment]
> Everything is explained in the Readme with official references, you can click on each hyperlinked text and open the relevant page. Closing this.

bro i instal and it dont add button to Start it to my desk top

**Comment by HotCakeX** [comment]
> > Everything is explained in the Readme with official references, you can click on each hyperlinked text and open the relevant page. Closing this.
> 
> bro i instal and it dont add button to Start it to my desk top

Who said there is going to be a button ?
