### ISSUE TITLE
[Bug]: Allow Grace Period for OS Version Requirement Check

### ISSUE THREAD

**Issue by starraiderx** [HotCakeX/Harden-Windows-Security#92]
### Tools category

Harden Windows Security Script

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Please explain the bug

The script mandates users to have the latest version of Windows installed. However, it's a known fact that Windows doesn't consistently distribute updates to all users at the same time. There can be delays for some users without any apparent reason. For instance, across my four devices, I consistently encounter this error:

Write-Error: You're not using the latest build of the Windows OS. A minimum build of 22621.2215 is required but your OS build is 22621.2134. Please go to Windows Update to install the updates and then try again.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/33199500/eedda718-4256-4b30-9013-f763d0cb5dd0)

To account for these Windows update inconsistencies, I recommend introducing a grace period in the script's requirements. For instance, permitting Windows builds that are Outdated for up to 2 weeks would be more accommodating for users who haven't received the latest update yet.

**Comment by HotCakeX** [comment]
Hi,
I just had to select that build number as minimum to make sure the features [added here](https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/v2023.08.20) are usable when the script tries to enable them.

In the future I will wait for them to be available without the need to toggle this button

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/b55bf747-fa5a-47ec-a191-765b48fac5ec)


I changed the build number requirement to `22621.2134` : https://github.com/HotCakeX/Harden-Windows-Security/pull/93

**Comment by starraiderx** [comment]
Off-topic a bit, but is there a way to force Windows updates? I still don't see any updates with this button enabled.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/33199500/5cc9b24f-568b-481d-b85c-5a86a6550a33)

**Comment by HotCakeX** [comment]
Oh, do you happen to be using MSI motherboard? MSI has a problem with their BIOS so MSFT stopped offering this update to those users until they release a new BIOS update for their hardware.

For me the update was installed around 5 days ago

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/94b714a9-4330-4491-9e47-25c5e74d158f)

**Comment by starraiderx** [comment]
Asus motherboard on my desktop. My laptops are Dell, Lenovo, HP so they use the corresponding proprietary BIOS. 
Probably, Microsoft just dislikes me xD.

**Comment by HotCakeX** [comment]
> Asus motherboard on my desktop. My laptops are Dell, Lenovo, HP so they use the corresponding proprietary BIOS. Probably, Microsoft just dislikes me xD.

Haha! it's okie, preview updates won't be a requirement again, will always stick to stable globally released builds :)
