### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by defconxt** [HotCakeX/Harden-Windows-Security#96]
### Tools category

Harden Windows Security Script

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Please explain the bug

Hi...there seems to be an issue with "Country IP Blocking" - starting here: https://github.com/HotCakeX/Harden-Windows-Security/blob/45e9438bc74bed782429880f99da2f0696dfcaea/Harden-Windows-Security.ps1#L1357

**Error output from powershell prompt:**

```Run Country IP Blocking category ?
1: Yes
2: No
3: Exit
Select an option: 1
Add countries in the State Sponsors of Terrorism list to the Firewall block list?
1: Yes
2: No
Select an option: 1
New-NetFirewallRule: C:\Users\redacted\Harden-Windows-Security.ps1:1372
Line |
1372 |  …             New-NetFirewallRule -DisplayName "$ListName IP range bloc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The network name cannot be found.
New-NetFirewallRule: C:\Users\redacted\Harden-Windows-Security.ps1:1373
Line |
1373 |  …             New-NetFirewallRule -DisplayName "$ListName IP range bloc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The network name cannot be found.
Add OFAC Sanctioned Countries to the Firewall block list?
1: Yes
2: No
Select an option: 1
New-NetFirewallRule: C:\Users\redacted\Harden-Windows-Security.ps1:1372
Line |
1372 |  …             New-NetFirewallRule -DisplayName "$ListName IP range bloc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The network name cannot be found.
New-NetFirewallRule: C:\Users\redacted\Harden-Windows-Security.ps1:1373
Line |
1373 |  …             New-NetFirewallRule -DisplayName "$ListName IP range bloc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The network name cannot be found.
```

I was able to successfully run the rest of the prompt with no issues...aside from the battle.net fix after I ran the TLS section.

**I did also check to make sure the NetSecurity Module is available as well:**
```
PS C:\Users\redacted> Get-Module -ListAvailable | Where-Object { $_.Name -eq 'NetSecurity' }
>>

    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.0.0.0               NetSecurity                         Core,Desk {Get-DAPolicyChange, New-NetIPsecAuthPr…
```

however to clarify (maybe related?) I did not choose to run the Windows Network section as I run my local network under private and run a plex server. I did not want to break any media streaming on my local network. To my understanding this breaks local discoverability.

Maybe using something more granular like https://www.henrypp.org/product/simplewall would be a better use case, unsure at this point.

Thanks for any advice, and if this is an issue on my end and not a bug then feel free to close this out.

**Comment by HotCakeX** [comment]
Hi,
I can't reproduce that issue, looks like a problem on your end such as an incompatible configuration etc., but not a bug in the module or script..
you can verify it too by running it on a clean OS installation.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/15f0eb93-1b4c-4530-ad88-f813d5d60457)

**Comment by HotCakeX** [comment]
> Alright, no problem...not sure what I would have changed to make it not compatible. Thanks for taking a look.

Of course, and sorry I couldn't help. If I had a case like that I wanted to debug, I'd take a clean installation, test the country blocking, if successful then apply my configurations one by one and after each of them test the country blocking again to see which one finally causes the problem.

on my side I've tested the module on physical machine, Hyper-V VM and Azure VMs, some have physical network adapter, some have only virtual adapters and some a mix of them.

If you do find the source of that problem let me know see if i can change something or put a check in the code so that it will behave differently.
